### ISSUE TITLE
C&C++   not support  IOS Device

### ISSUE THREAD

**Issue by FutureOne011** [kiwix/iOS#1]
Project C & C ++ folder .a library does not support iOS real machine (arm64, armv7), I hope you provide library support for iPhone , thank you!

**Comment by kelson42** [comment]
<adventis> Hello
<adventis> I have some problem to run kiwix (iOS) on my device. So it's successful run on iPhone Simulator but when I try to run on real device it says that didn't support armv7, armv7s and arm64 architecture
<adventis> Please help me to figure out of this problem
<adventis> it's say that in these src files didn't support needed architectures: stringTools.cpp, reader.cpp, pathTools.cpp
<Kelson> adventis: hi
<Kelson> adventis: which kind of device do you have?
<adventis> iPad mini

**Comment by kvofreelance** [comment]
Hello
I have the same issue. In attached files are screenshots with errors in xcode
![Uploading Screen Shot 2016-01-16 at 12.24.42 PM.png…]()
![Uploading Screen Shot 2016-01-16 at 12.24.56 PM.png…]()

**Comment by kvofreelance** [comment]
Hello
I have the same issue. In attached files are screenshots with errors in xcode
![screen shot 2016-01-16 at 12 24 56 pm](https://cloud.githubusercontent.com/assets/3186871/12371938/20d44dee-bc4e-11e5-9cac-f4f50760022d.png)
![screen shot 2016-01-16 at 12 24 42 pm](https://cloud.githubusercontent.com/assets/3186871/12371939/20dec012-bc4e-11e5-921b-ebd008ac8234.png)

**Comment by automactic** [comment]
To compile kiwix on your Mac, you need to have .a files containing binaries targeting the type of iOS device you want kiwix to run on. 
BTW, where did you guys get the binary files?

**Comment by kvofreelance** [comment]
I took .a files in next source:
1. liblzma.a - I downloaded src from http://tukaani.org/xz/ (version 5.2.2). I used your build-xz.sh and compiled universal library which support "armv7 armv7s arm64 i386 x86_64" arch. After I copied liblzma.a file and folder "lzma" with headers to project.
2. libicudata.a, libicui18n.a, libicuio.a, libicule.a, libiculx.a, libicutu.a, libicuuc.a these files i compiled for "armv7 armv7s arm64 i386 x86_64" using instruction from https://github.com/zhm/icu-ios
3. libzim.a - I downloaded src from https://gerrit.wikimedia.org/r/p/openzim.git and compiled it using build-libzim.a. Also I modified this script and replace -L/Users/chrisli/Developer/xz-5.2.0/build/${ARCH}/lib" on folder where I compiled liblzma.a library.
After I added to project all needed headers files. In Kiwix build settings I set Valid architectures to "arm64 armv7 armv7s".
When I try run app on real device(iPad mini) I got errors which you see on screenshots.
Please give me instructions how compile libraries and run app on real devices.

P.S.: Also, if you can please give me your skype, email etc. We can work together and will prepare instructions or universal script to build missing libraries and close this issue.

Thank you

**Comment by kvofreelance** [comment]
@automactic  can you sent me builded libraries(with support armv7 armv7s arm64) an headers which you used to run app on real device?
P.S.: My email: kvofreelance@gmail.com
