### ISSUE TITLE
Kiwix should open automatically a content in some case

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#11]
1 - no content is already loaded in the HTML view
2 - a (first) content just finish to download
3 - this triggers the load of the welcome page
4 - at the time the user leaves the library, the content is already loaded and the user does not need to search to start "surfing".

This is necessary to avoid a few users to search how to "open" the content they just have downloaded - not all users intuitively understand that they have to click on the search box an put a term to search.

**Comment by automactic** [comment]
Implemented in build 1547

**Comment by automactic** [comment]
Done in 1.6 release

**Comment by kelson42** [comment]
Applying step-by step the procedure of the ticket and it does not work: although a ZIM file just finished to download the HTML render view is still empty.

**Comment by automactic** [comment]
Main page is opened only when first book finish downloading or being added using itunes

**Comment by kelson42** [comment]
OK, then I should remove all my books to check this. OK I would not have limited that to the first book... But I think 70% of the problem is fixed like this.
