### ISSUE TITLE
Provide IPA file for iOS releases

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#12]
Feedback from a user:
===
Can you send me 1.2v of Kiwix app for ipad in ipa format? Because I have ios 8.2, and now I can't update my iPad to iOS 9
===

Would that be possible?

**Comment by automactic** [comment]
Kiwix is targeting iOS 9.0 and above, so it won't be able to run in iOS 8.2. Why you cannot upgrade to iOS 9?
