### ISSUE TITLE
Download content got stuck

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#13]
I have achieve to get content stuck in the download queue. That means that I was not able to continue the download and not able to delete the (paused) download.

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/1029718/16311702/e0ebf6d6-3971-11e6-8ae3-a317898cda48.jpeg)

Probably the root cause is that:
1 - I have started a download of a content available in the the online library
2 - This content has been superseed by a newer version (and removed from the online library)
3 - The app gets lost because of the lack of information in the online library

**Comment by automactic** [comment]
fixed in version 1.6 build 705, to be tested.

**Comment by automactic** [comment]
Fixed in 1.6 release

**Comment by kelson42** [comment]
Thx for this important fix.
