### ISSUE TITLE
Build instructions are missing

### ISSUE THREAD

**Issue by jberkel** [kiwix/iOS#16]
Looks like libkiwix needs to be integrated into the project somehow – would be great to have this documented.

**Comment by kelson42** [comment]
Yes. The plan is to create a dedicated repo for the libkiwix which will provide all ports with the necessary binary library. To be done in the next 4 weeks.

**Comment by jberkel** [comment]
OK, thanks! But why a binary library and not a pod or submodule?

**Comment by kelson42** [comment]
it might be integrated in the git as a submodule... this is still not clear to me exactly which form it will take. But I want ultimately to be able to package the kiwix-lib separately.

**Comment by automactic** [comment]
@jberkel, as I understand, the plan is to have a C++/C repo containing everything needed to read & search zim files, and to be used in all platforms (iOS, Android, macOS, Linux & Win). So we cannot use CocoaPods or create sub-Xcode projects.

**Comment by kelson42** [comment]
So we are late on the create of a portable libkiwix, but this is still on the agenda. Work should start in november.
