### ISSUE TITLE
Kiwix hangs w/out internet or wifi connection 

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#2]
in iOS there seems to be an issue when in offline mode or on roaming. Using version 1.2, Kiwix hangs when there is no internet or wifi connection available.

Examples:

Offline Mode, no wifi -> hangs
Offline Mode, wifi connection(without internet connection!) -> Works
Roaming (Data off), no wifi -> hangs
3G, Wifi, etc -> Works

There is no need for an active internet connection, but apparently some some sort of connection to make it work. But as a fun fact, for some reason there is data-traffic shown in the settings for Kiwix.

---
First reported on Sourceforge https://sourceforge.net/p/kiwix/bugs/932/

**Comment by kelson42** [comment]
I don't have a SIM card on my iphone, but without wiki it seems to work with the last testflight version. @automactic, do you confirm you have fixed that problem?

**Comment by automactic** [comment]
No, I think the problem only appears when 1) a few day's after initial install 2) when there is completely no internet connection.

**Comment by kelson42** [comment]
Is that complicated to fix. This sounds to be a serious issue to have an offline app which can not work correctly without internet at all.

**Comment by automactic** [comment]
This issue is fixed in v1.3. :-)
