### ISSUE TITLE
Implement a way to clean the history

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#23]
both search & navigation history.

**Comment by kelson42** [comment]
Assuming it works :) Thx for being so reactive!

**Comment by kelson42** [comment]
It seems to clean only the search history, not the navigation history. To do so, you have to force to stop the application, which is not really user friendly.

**Comment by automactic** [comment]
Yes, only clean search history. Because it is in setting -> search -> history.

Search history is persist on disk, so it make sense to clean it. So does article reading history. Should navigation history be able to be cleared? (You don't clear a tab's navigation stack in a browser) I don't know...

**Comment by kelson42** [comment]
What matters is to provide a solution to clean navigation traces: all kind of them. To my opinion one option to clear both navigation and search is goo and. Current tabs are left open - but history is removed (similar workflow like in firefox).

**Comment by automactic** [comment]
Both clear browsing history and search history function is added in commit 4d05217d95b34729d84286f81a0e95d4ea8222fe

**Comment by kelson42** [comment]
@automactic  1.8.1 dies if I click on 'clear search history'

**Comment by automactic** [comment]
@kelson42 Oops...

**Comment by automactic** [comment]
would also be useful if there is an option to turn off search history

**Comment by kelson42** [comment]
@automactic To me two things seem to still do not work correctly:
* the back/forward arrows keep their blue color (although the history is cleared), they should be grey
* the current page loaded is removed, it should be kept.

**Comment by automactic** [comment]
This is fixed. Another planned feature is to disable search history at all.
