### ISSUE TITLE
Download does not recover with 1.8

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#36]
Steps:
1 - No access to internet
2 - Start download of a content
3 - I get in the "download" tab, the content with "error" (I think it should be written "pending")
4 - At the time wifi is again available the download does not start and there is not way to start it (except removing the content and restarting the download).

**Comment by automactic** [comment]
@kelson42, is this issue solved in the last beta?

**Comment by kelson42** [comment]
fixed
