### ISSUE TITLE
Table of Index should not release on <h*> "id" attribute

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#37]
The table of index does not work correctly for the Vikida ZIM files (see https://github.com/kiwix/mwoffliner/issues/24). The reason is that <h*> structure DOM nodes do not have an id.

The "id" attribute is not mandatory in HTML and the HTML we have in ZIM files is not generated by us, but by the Mediawiki backend (in the case of Wikipedai). Kiwix should therefore not rely on it.

The app should simply works with indexes (of item in list given by something like getElementsByTagName()).

**Comment by automactic** [comment]
Is it safe to assume that all `<h*>` are children of `#mw-content-text`?

**Comment by kelson42** [comment]
@automactic It's not. The assumption you can do are the one which are in the HTML specs.

**Comment by automactic** [comment]
Then it is not possible for me to get the positional / hierarchical relationship between headings, I think.

**Comment by kelson42** [comment]
@automactic The hierarchical, this is really easy (this is DOM tree). The positional, if you explain me how you proceed, maybe I can help you.

**Comment by automactic** [comment]
The hierarchical is easy? Really? Teach me how, please! As I understand, you can only getElementsByTagName, so will not be able to figure out which h2 is under which h1 for example.

**Comment by kelson42** [comment]
This should be possible with https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll. Here is how it works for Android https://github.com/kiwix/kiwix/commit/1be5e978b9ec89cba89fee2934642c0303bc6cf8

**Comment by automactic** [comment]
Done in version 1.8
