### ISSUE TITLE
how to get static libs

### ISSUE THREAD

**Issue by jiangmingz** [kiwix/iOS#42]
<img width="185" alt="libs" src="https://cloud.githubusercontent.com/assets/187824/20358242/04ad7ea2-ac66-11e6-905e-229456b580e3.png">

**Comment by kelson42** [comment]
@automactic ?

**Comment by jiangmingz** [comment]
l want get build static file or method  in mac

**Comment by jiangmingz** [comment]
l want get build static file or method  in mac for ios

**Comment by jiangmingz** [comment]
l want get build static file or method  in mac for ios

**Comment by automactic** [comment]
We hope to provide a better solution with [libKiwix](https://github.com/kiwix/kiwix-lib) in the future, stay tuned.
