### ISSUE TITLE
Going back to a page should bring you to the same vertical scrolling position

### ISSUE THREAD

**Issue by pgorsira** [kiwix/iOS#49]
This is how Wikipedia works in iOS Safari. If you navigate to a new page, then press the back button, it will take you back to the same vertical scrolling position you were at when you originally left. Kiwix instead returns you to the top of the page.

Great software btw!

**Comment by automactic** [comment]
Yes, it should. I will try to fix it in the future.

**Comment by automactic** [comment]
Hopefully fixed in 1dc0ab61e274f5dfd3de1037a3b031500ca95a8c

**Comment by pgorsira** [comment]
That's great to hear - appreciate you guys taking in the feedback.

**Comment by kelson42** [comment]
It seems to save somehow the vertical position, but it does not come back at the exact position.

**Comment by automactic** [comment]
I think this is fixed. Would you like to confirm it? @kelson42

**Comment by kelson42** [comment]
Yes, works fine :)
