### ISSUE TITLE
In case of cancelled downloads, the tmp file is not removed

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#5]
the Kiwix app is using 22GB of space on my iphone however I only have two libraries downloaded (Wikinews at 1.35GB and Wikivoyage at 588.4 MB)

I did try downloading hte Wikipedia library 55.6 GB but it failed (a few times) I suspect that the download failed but kept the partial files on the app. 

Firstly report here:
https://sourceforge.net/p/kiwix/discussion/604122/thread/82a1fa50/?limit=25#2749

**Comment by kelson42** [comment]
@automactic What is the status on this. Do you confirm?

**Comment by automactic** [comment]
Note: When downloading a big file, the temp file is not stored in the app's sandbox., but somewhere in the system. When pausing a task, the system daemon that handles the download produce a blob of data (around 4000-5000 bytes) that can be stored and later used as info to resume the download task. 

In other words, I have no control over the temp file. If I remember correctly, the temp file will be purged when the system need more disk space or when the download task is inactive for 7 days.
