### ISSUE TITLE
Download Mode: Don't ask for «Cellular» on WiFi only models 

### ISSUE THREAD

**Issue by martin8032** [kiwix/iOS#50]
Each time I start a download in v1.8 I have to choose between «WiFi Only» and «WiFi + Cellular». In my case this does not make sense since my iPad is a WiFi only model. The app should only ask this question if cellular is a real option which means a) the hardware is present and b) a 3G/4G connection is currently established.

**Comment by automactic** [comment]
Good point, totally missed it. Will fix in next build

**Comment by automactic** [comment]
It was fixed in 14bbbd29bf3b38f2c7242ff4de9a2cdcfd8dbb48. 
@martin8032, please test it after the next beta is out. I don't have a non-cellular iPad, so can't really test on real device. Thanks!
