### ISSUE TITLE
Download is broken

### ISSUE THREAD

**Issue by martin8032** [kiwix/iOS#54]
In v1.8.4073 there are two issues when downloading a package from the cloud:

On iPad WiFi: When I click on the «Download» command in the dropdown menu, the app crashes immediately.

On iPhone: When I choose «WiFi Only», nothing happens although the iPhone has a WiFi connection. (When I choose «WiFi + Cellular», the download starts as usual.)

**Comment by kelson42** [comment]
I can only "wifi" with my test device... but it seems indeed impossible with last testflight to download with wifi. The download simply deos not start and does not appear in the list of downloads.

**Comment by automactic** [comment]
I forgot to uncomment a line. Issue is supposed to be fixed in a09b8f46b1e1142eb18afaea80f79cb80e4f706b. 

Uploading new beta build...

**Comment by martin8032** [comment]
Works in the latest release (both on iPad WiFi and iPhone).

Thanks!

**Comment by automactic** [comment]
@martin8032 Any time!
