### ISSUE TITLE
[1.5] Crash by deleting files

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#6]
Steps:
* Uninstall Kiwix
* Install last version of Kiwix from testflight (1.5)
* Download many content
* Go to the local file list in thelibrary
* Delete a content

You get:
* Content is deleted but app crashs/stops immediatly

You want:
* Content deleted, but no crash

**Comment by automactic** [comment]
This might be caused by a compile issue, because after I clean and recompile the project, the issue disappeared. Let's try re-upload the app again.

**Comment by automactic** [comment]
This issue should be fixed in BUILD 201605081. @kelson42, could you please confirm?

**Comment by kelson42** [comment]
It is :)
