### ISSUE TITLE
Tell user the download has started when clicking on book

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/iOS#63]
I think it's essential that when a user clicks on a book to download there should be some UI feedback that the download has started and where exactly can you track your download. For example, maybe red count banner on the downloads icon at the top.

**Comment by automactic** [comment]
We have talked about this issue in #52. I think the next step is to consolidate the downloading view and the cloud tab. (start a download, book does not disappear from cloud tab, show a progress indicator)

**Comment by EladKeyshawn** [comment]
@automactic Ok hope it'll be solved soon.
