### ISSUE TITLE
Better utilize URLSession's discrepancy feature

### ISSUE THREAD

**Issue by kelson42** [kiwix/iOS#7]
Tested on 1.5.

Steps:
1 - Download 5 content
2 - Stop the app before the download have completed (no hibernation)
3 - Restart the app
4 - Download are paused, clikc on each of them to resume the download

I get:
- Almost impossible to resume the downloads. I have to click many times, stronger, more preciser... I don't know exactly and I have only achieved to resume 2/5 downloads

I should get:
- 5 clicks and all the downloads restarts quickly (or are queued)

**Comment by kelson42** [comment]
This is related to iOS 'discrepency' feature. 'Discrepency' was disabled in 1.5.1 and problem should be investigated for next version as 'discrepency' a really nice feature we want to benefit from.

**Comment by automactic** [comment]
in 1.8 and up, user initiated downloads have `discrepancy ` turned off, since it is very likely user will want to see download start right away.

**Comment by kelson42** [comment]
@automactic Nice
