### ISSUE TITLE
impossible to switch between index an title search

### ISSUE THREAD

**Issue by Kontor23** [kiwix/iOS#9]
Tested on 1.5.

It is impossible to switch between indexed search and title search

also there is no possibility to change between an AND or an OR search via + sign

**Comment by automactic** [comment]
In v1.6, app is going to perform title search and indexed search (if possible), and combine the result together using a ranking algorithm. o we can get the best of both worlds.

**Comment by automactic** [comment]
The above mentioned 2 type search and result combine algorithm has been implemented in 1.6 release

**Comment by kelson42** [comment]
Really nice feature!
